name: project
on:
  push:
    branches:
    - init
jobs:
    build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 💡 Creando proyecto en git
        run: |
         curl -X POST https://api.github.com/repos/${{ github.repository }}/projects \
         -H "Accept: application/vnd.github.v3+json" \
         -H "Authorization: token ${{ secrets.MY_GITHUB_PAT }}" \
         -d '{
           "name": "${{ github.event.repository.name }}",
           "body": "Este es un proyecto creado automáticamente con GitHub Actions."
         }'
      - name: 💡 Creando proyecto en git 2
        run: |
         curl -X POST -H "Authorization: bearer ${{ secrets.MY_GITHUB_PAT }}" \
         -H "Content-Type: application/json" \
         -H "Accept: application/vnd.github.v3+json" \
         https://api.github.com/graphql \
         -d '{
           "query": "mutation { createProjectV2(input: {ownerId: \"${{ github.repository_owner }}\", title: \"${{ github.event.repository.name }}\"}) { projectV2 { id } } }"
         }'
